# Generated by Django 5.0.6 on 2024-06-26 01:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('celular', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='El número debe tener el formato: +569xxxxxxxx', regex='^\\+569\\d{8}$')], verbose_name='Teléfono')),
                ('rut', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato: 12345678-0', regex='^\\d{7,8}-[0-9kK]{1}$')], verbose_name='RUT')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('pass1', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('pass2', models.CharField(max_length=128, verbose_name='Confirmar Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, max_length=255, upload_to='fotosProductos/', verbose_name='Imagen')),
                ('nom_producto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=500)),
                ('cantidad', models.CharField(max_length=5)),
                ('precio', models.CharField(max_length=45)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
            ],
        ),
    ]
