# Generated by Django 5.0.6 on 2024-06-27 23:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=1)),
                ('Direccion', models.CharField(blank=True, default='', max_length=100)),
                ('Fecha', models.DateField(default=datetime.datetime.today)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
    ]
